return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "gdscript",
      "godot_resource",
      "gdshader",
      "lua",
      "vim",
      "javascript",
      "typescript",
      "python",
      "c",
      "cpp",
      "html",
      "css",
      "json",
    },
    highlight = { enable = true },
    indent = { enable = true },
    autopairs = { enable = true },
    sync_install = false,
    auto_install = true,
  },
}
